from tkinter import *

root = Tk()

b1=Button(root,text='login',fg='black')
b1.place(x=80,y=250)
label1 =Label(root,text="S NO.", fg='Black')
label1.place(x=15,y=20)
entry1=Entry(root)
entry1.place(x=70,y=22)
label2 =Label(root,text="NAME", fg='Black')
label2.place(x=15,y=60)
entry2=Entry(root)
entry2.place(x=70,y=60)
label3 =Label(root,text="ROLL NO", fg='Black')
label3.place(x=15,y=100)
entry3=Entry(root)
entry3.place(x=70,y=100)
label4 =Label(root,text="GENDER", fg='Black')
label4.place(x=15,y=140)
Radiobutton(root,text="Male",value=1).place(x=70,y=138)
Radiobutton(root,text="Female",value=2).place(x=130,y=138)
label5 =Label(root,text="BRANCH", fg='Black')
label5.place(x=15,y=180)
list_of_Branches=[ 'CSE' ,'ELECTRICAL' , 'CIVIL' ,'MECHANICAL' ,'AUTO MOBILE']
c=StringVar()
droplist=OptionMenu(root,c, *list_of_Branches)
droplist.config(width=15)
c.set('Select your Branch')
droplist.place(x=70,y=175)
root.mainloop()
